# Generated by Django 4.2.7 on 2023-12-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_orderitem_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_management.payment'),
        ),
    ]
