# Generated by Django 4.2.7 on 2023-12-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_orderitem_payment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_details',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel_reason',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_management.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('PROCESSING', 'Order Processing'), ('SHIPPED', 'Order Shipped'), ('OUT FOR DELIVERY', 'out for delivery'), ('DELIVERED', 'Order Delivered'), ('CANCELLED', 'Order Cancelled')], default='New', max_length=20),
        ),
    ]
