# Generated by Django 4.2.7 on 2023-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_remove_order_order_details_orderitem_cancel_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('PROCESSING', 'Order Processing'), ('SHIPPED', 'Order Shipped'), ('OUT FOR DELIVERY', 'out for delivery'), ('DELIVERED', 'Order Delivered'), ('CANCELLED', 'Order Cancelled')], default='New', max_length=20),
        ),
    ]
