# Generated by Django 4.2.7 on 2023-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_remove_order_order_status_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('PROCESSING', 'Order Processing'), ('SHIPPED', 'Order Shipped'), ('OUT FOR DELIVERY', 'out for delivery'), ('DELIVERED', 'Order Delivered'), ('CANCELLED', 'Order Cancelled')], default='PLACED', max_length=20),
        ),
    ]
