# Generated by Django 4.2.7 on 2023-12-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_id',
            field=models.CharField(default='#0000000', max_length=120),
        ),
    ]
