# Generated by Django 4.2.7 on 2023-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_orderitem_order_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cod_payment_id',
            new_name='payment_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('RazorPay', 'Razor Pay'), ('SeamPay', 'Seam pay')], max_length=100),
        ),
    ]
