# Generated by Django 4.2.7 on 2023-12-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_alter_payment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('PROCESSING', 'Order Processing'), ('SHIPPED', 'Order Shipped'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Order Delivered'), ('CANCELLED', 'Order Cancelled'), ('RETURNED', 'Order Returned')], default='PLACED', max_length=20),
        ),
    ]
