# Generated by Django 4.2.7 on 2023-12-13 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_rename_cod_payment_id_payment_payment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_wallet_amount_alter_wallet_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_balance',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_management.orderitem'),
        ),
        migrations.CreateModel(
            name='SeamPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
