# Generated by Django 4.2.7 on 2023-12-13 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_wallet_wallet_balance_alter_wallet_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='seampay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.seampay'),
        ),
    ]
