# Generated by Django 4.2.7 on 2023-12-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_wallet_seampay_seampay_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seampay',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallet',
            name='seampay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.seampay'),
        ),
    ]
