# Generated by Django 4.2.7 on 2023-12-27 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0007_remove_seampay_wallet_wallet_seampay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_referrel', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
