# Generated by Django 4.2.7 on 2023-12-27 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0008_referrel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referrel',
            new_name='Referral',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='my_referrel',
            new_name='my_referral',
        ),
    ]
