# Generated by Django 4.2.7 on 2023-12-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_rename_referrel_referral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
