# Generated by Django 4.2.7 on 2023-11-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('category_img', models.ImageField(blank=True, null=True, upload_to='imgs/category_imgs')),
                ('slug', models.SlugField(max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_manage.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
