# Generated by Django 4.2.7 on 2023-12-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_manage', '0002_categoryoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category_manage.category'),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
