# Generated by Django 4.2.7 on 2023-11-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atrribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
                ('brand_img', models.ImageField(default='', upload_to='brand_logo/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=49, unique=True)),
                ('product_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='mproducts/')),
                ('product_description', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('product_catg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category_manage.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=30, unique=True)),
                ('color', models.TextField(blank=True, max_length=50)),
                ('ram', models.TextField(blank=True, max_length=50)),
                ('storage', models.TextField(blank=True, max_length=50)),
                ('os', models.TextField(blank=True, max_length=50)),
                ('screen_size', models.TextField(blank=True, max_length=50)),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.IntegerField()),
                ('thumbnail_img', models.ImageField(upload_to='varient_img/')),
                ('product_varient_slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attribute_value', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.atrribute')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('model_id__isnull', False)), fields=('product', 'model_id'), name='unique_skuid_must_be_provided'),
        ),
    ]
