# Generated by Django 4.2.7 on 2023-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product_varient_slug',
            field=models.SlugField(blank=True, max_length=350, unique=True),
        ),
    ]
